<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\BuildingBlocks\EventBus\EventBus.Messages\EventBus.Messages.csproj" />
      <ProjectReference Include="..\..\..\BuildingBlocks\Infrastructure\Infrastructure.csproj" />
      <ProjectReference Include="..\Notification.Application\Notification.Application.csproj" />
      <ProjectReference Include="..\Notification.Domain\Notification.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Protobuf Include="..\..\Customer\Customer.Presentation\Grpc\Protos\customer_info.proto">
        <Link>Grpc\Protos\customer_info.proto</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Protobuf>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Grpc.Tools" Version="2.72.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <Protobuf Include="..\..\Product\Product.Presentation\Grpc\Protos\products.proto">
        <Link>Grpc\Protos\products.proto</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Protobuf>
    </ItemGroup>

</Project>
