services:
  #product-db
  product-db:
    container_name: product-db
    environment:
      MYSQL_ROOT_PASSWORD: "Anhvu2182004@"
    restart: always
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/sqlserver/data
  
  #customer-db
  customer-db:
    container_name: customer-db
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "Anhvu2182004@"
      POSTGRES_DB: "DiscountDb"
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  
  #basket-db
  basket-db:
    container_name: basket-db
    restart: always
    ports:
      - "6380:6379"
  
  #order-db
  order-db:
    container_name: order-db
    environment:
      SA_PASSWORD: "Anhvu2182004@"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1434:1433"
    volumes:
      - sqlserver-data:/var/lib/sqlserver/data
  
  #inventory-db
  inventory-db:
    container_name: inventory-db
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/var/lib/mongo/data
  
  #infrastructure section
  rabbitmq:
    container_name: rabbitmq
    restart: always
    ports:
      - "5673:5672"
      - "15673:15672"
        
  pgadmin:
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "anhvu2182004@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin12345"
    restart: always
    ports:
      - "5051:80"
    volumes:
      - pgadmin-data:/root/.pgadmin
        
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8081:8000"
      - "9001:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
        
  elasticsearch:
    container_name: elasticsearch
    environment:
      - xpack.monitoring.enabled=true
      - xpack.watcher.enabled=false
      - discovery.type=single-node
    ports:
      - "5778:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
  
  kibana:
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:5778
    ports:
      - "5602:5601"
    depends_on:
      - elasticsearch
