services:
  #database section
  product-db:
    image: mysql:8.0.29
  
  customer-db:
    image: postgres:alpine3.16
  
  basket-db:
    image: redis:alpine
  
  order-db:
    image: mcr.microsoft.com/mssql/server:2019-latest
  
  inventory-db:
    image: mongo
  
  #infrastructure section
  rabbitmq:
    image: rabbitmq:3-management-alpine
  
  pgadmin:
    image: dpage/pgadmin4
  
  portainer:
    image: portainer/portainer-ce
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.2
  
  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.2
  
  #microservices api section
  product-api:
    image: ${DOCKER_REGISTRY-}product-api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Services/Product/Product.API/Dockerfile

#network section
networks:
  default:
    name: v-microservices
    driver: bridge

#volumes section
volumes:
  sqlserver-data:
    name: sqlserver-data
  mysql-data:
    name: mysql-data
  postgres-data:
    name: postgres-data
  portainer-data:
    name: portainer-data
  elasticsearch-data:
    name: elasticsearch-data
  jaeger-data:
    name: jaeger-data
  mongo-data:
    name: mongo-data
  pgadmin-data:
    name: pgadmin-data
